name: Pipeline smoke test

on: [push]

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect data from the catalog
      run: python NomismaPipeline.py

  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rdflib

    - name: Ensure that RDF is not malformed
      run: python -m rdflib.tools.rdfpipe princeton-nomisma.rdf voID.rdf

